export type MonthPlan = {
  plantNow: string[];
  startInTrays: string[];
  harvest: string[];
  prepareForNextMonth: string[];
};

export type RegionData = {
  id: string;
  name: string;
  zone: string;
  climateReality: string[];
  growsWell: string[];
  seedsToStock: string[];
  directSowNow: string[];
  startInTraysNow: string[];
  transplantsToBuyNow: string[];
  thisWeeksTasks: string[];
  prepareNext: string[];
  heatFrostNotes: string[];
  months: Record<string, MonthPlan>;
};

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

export type MonthName = (typeof MONTHS)[number];

// ─── Anderson / Redding / Red Bluff ───────────────────────────────────────────

const andersonMonths: Record<MonthName, MonthPlan> = {
  January: {
    plantNow: [
      "Garlic (if not done in fall)",
      "Peas",
      "Fava beans",
      "Spinach",
      "Lettuce",
      "Kale",
      "Mustard greens",
      "Radishes",
      "Cilantro",
      "Onion sets",
    ],
    startInTrays: ["Onions", "Leeks", "Broccoli", "Cabbage", "Cauliflower"],
    harvest: [
      "Overwintered kale and chard",
      "Winter greens",
      "Root vegetables planted in fall",
      "Citrus",
    ],
    prepareForNextMonth: [
      "Clean up winter beds",
      "Add compost to planting areas",
      "Order seeds now — good selections sell out",
      "Prune dormant fruit trees",
      "Check irrigation lines for winter damage",
    ],
  },
  February: {
    plantNow: [
      "Peas",
      "Spinach",
      "Lettuce",
      "Radishes",
      "Carrots",
      "Beets",
      "Turnips",
      "Chard",
      "Arugula",
      "Cilantro",
    ],
    startInTrays: [
      "Tomatoes (late February)",
      "Peppers",
      "Eggplant",
      "Basil",
      "Broccoli",
      "Cabbage",
    ],
    harvest: [
      "Winter greens",
      "Kale",
      "Citrus",
      "Overwintered brassicas",
    ],
    prepareForNextMonth: [
      "Set up irrigation before the season gets away from you",
      "Build or repair trellises for peas and beans",
      "Prep tomato bed with compost and amendments",
      "Get drip system running and tested",
    ],
  },
  March: {
    plantNow: [
      "Peas",
      "Beets",
      "Carrots",
      "Chard",
      "Lettuce",
      "Spinach (early month)",
      "Potatoes",
      "Onion sets",
      "Turnips",
    ],
    startInTrays: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Basil",
      "Summer squash",
      "Cucumbers",
      "Melons",
    ],
    harvest: [
      "Spring greens",
      "Peas starting",
      "Kale",
      "Broccoli",
      "Early lettuce",
    ],
    prepareForNextMonth: [
      "Build tomato cages",
      "Get shade cloth on hand — you will need it",
      "Order summer seeds if you haven't",
      "Start watching last frost dates closely",
    ],
  },
  April: {
    plantNow: [
      "Beans (after last frost, usually mid-April)",
      "Beets",
      "Carrots",
      "Chard",
      "Summer squash",
      "Zucchini",
      "Corn (mid-late April)",
    ],
    startInTrays: [
      "Cucumbers",
      "Melons",
      "Winter squash",
      "Pumpkins",
      "Sunflowers",
      "Zinnias",
      "Marigolds",
      "Cosmos",
    ],
    harvest: [
      "Lettuce",
      "Peas",
      "Spring greens",
      "Asparagus",
      "Early radishes",
    ],
    prepareForNextMonth: [
      "Set up tomato cages and stakes before plants need them",
      "Check drip irrigation emitters",
      "Plan for summer water schedule — heat comes fast here",
      "Start mulching beds",
    ],
  },
  May: {
    plantNow: [
      "Beans (succession planting)",
      "Cucumbers",
      "Summer squash",
      "Zucchini",
      "Corn",
      "Sunflowers",
      "Zinnias",
      "Basil",
      "Okra (late May)",
    ],
    startInTrays: [],
    harvest: [
      "Peas (final harvest before heat)",
      "Lettuce (bolt watch — harvest before it turns bitter)",
      "Beets",
      "Carrots",
      "Spring greens",
      "Early beans",
    ],
    prepareForNextMonth: [
      "Transplant tomatoes, peppers, and eggplant if you haven't",
      "Mulch everything — bare soil bakes fast here",
      "Set up watering schedule before summer heat locks in",
      "Pull any bolting spring crops and replant with summer crops",
    ],
  },
  June: {
    plantNow: [
      "Okra",
      "Cowpeas",
      "Armenian cucumbers",
      "Lemon cucumbers",
      "Beans (succession)",
      "Watermelon",
      "Sunflowers",
      "Zinnias",
      "Marigolds",
    ],
    startInTrays: [
      "Broccoli (late June for fall — yes, it's still hot, start anyway)",
      "Cabbage for fall",
      "Cauliflower for fall",
    ],
    harvest: [
      "Zucchini",
      "Beans",
      "Cucumbers",
      "Early tomatoes",
      "Herbs",
      "Beets",
      "Garlic (late June)",
    ],
    prepareForNextMonth: [
      "Fall brassica timing matters more than it feels like right now",
      "Order garlic varieties for fall planting",
      "Plan fall garden layout",
      "Make sure irrigation is set to deep, infrequent watering",
    ],
  },
  July: {
    plantNow: [
      "Cowpeas",
      "Okra",
      "Armenian cucumbers",
      "Beans (last succession)",
    ],
    startInTrays: [
      "Broccoli (for fall — 10-12 weeks before transplant date)",
      "Cabbage",
      "Kale",
      "Cauliflower",
    ],
    harvest: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Cucumbers",
      "Zucchini",
      "Beans",
      "Melons",
      "Basil",
      "Herbs",
    ],
    prepareForNextMonth: [
      "Order fall seeds now",
      "Prep fall beds while you have time",
      "Plan garlic order — place it early",
      "Check compost pile and turn if needed",
    ],
  },
  August: {
    plantNow: [
      "Cowpeas (last planting)",
      "Beans (last succession)",
      "Radishes (late August)",
    ],
    startInTrays: [
      "Broccoli",
      "Cabbage",
      "Kale",
      "Chard (for fall)",
      "Collards",
    ],
    harvest: [
      "Tomatoes (peak)",
      "Peppers",
      "Watermelon",
      "Eggplant",
      "Cucumbers (tapering off)",
      "Winter squash (check for maturity)",
      "Sweet corn",
    ],
    prepareForNextMonth: [
      "Clear spent summer beds and add compost",
      "Order garlic now",
      "Plan strawberry expansion — plant in September",
      "Make compost from summer plant debris",
    ],
  },
  September: {
    plantNow: [
      "Carrots",
      "Beets",
      "Chard",
      "Lettuce",
      "Radishes (mid-late September)",
      "Turnips",
      "Spinach (late September)",
    ],
    startInTrays: ["Kale", "Chard", "Spinach", "Pac choi"],
    harvest: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Winter squash (curing)",
      "Pumpkins",
      "Sweet potatoes",
    ],
    prepareForNextMonth: [
      "Prep garlic beds — plant in October",
      "Put strawberry plants in now for next year",
      "Adjust irrigation as temperatures drop",
      "Transplant fall brassicas started in July/August",
    ],
  },
  October: {
    plantNow: [
      "Garlic",
      "Onion sets",
      "Radishes",
      "Spinach",
      "Lettuce",
      "Carrots",
      "Peas (late October)",
      "Fava beans",
      "Cover crop mix",
    ],
    startInTrays: ["Onions (late October)"],
    harvest: [
      "Winter squash and pumpkins",
      "Fall greens",
      "Peppers (last of them)",
      "Late tomatoes",
      "Herbs before frost",
    ],
    prepareForNextMonth: [
      "Plant cover crops in empty beds",
      "Save seeds before frost takes the last tomatoes and peppers",
      "Get garlic in the ground",
      "Order onion seeds for January starts",
    ],
  },
  November: {
    plantNow: [
      "Garlic (if not done)",
      "Fava beans",
      "Peas",
      "Spinach",
      "Kale",
      "Chard",
      "Lettuce",
    ],
    startInTrays: ["Onions (late November)"],
    harvest: [
      "Fall greens",
      "Broccoli",
      "Chard",
      "Kale",
      "Root vegetables",
      "Late citrus",
    ],
    prepareForNextMonth: [
      "Mulch beds with straw to protect roots",
      "Protect young citrus from frost",
      "Plan next year's layout now while it's quiet",
      "Order seeds for the new year",
    ],
  },
  December: {
    plantNow: [
      "Garlic (last chance)",
      "Peas",
      "Fava beans",
      "Lettuce",
      "Spinach",
    ],
    startInTrays: [],
    harvest: [
      "Winter greens",
      "Citrus",
      "Kale",
      "Chard",
      "Root vegetables in ground",
    ],
    prepareForNextMonth: [
      "Order seeds — do this in December so you have what you want",
      "Plan bed layout for next year",
      "Service drip irrigation and flush lines",
      "Rest — January comes fast",
    ],
  },
};

// ─── Sacramento Valley ─────────────────────────────────────────────────────────

const sacramentoMonths: Record<MonthName, MonthPlan> = {
  January: {
    plantNow: ["Peas", "Fava beans", "Onion sets", "Garlic (last chance)", "Spinach", "Lettuce"],
    startInTrays: ["Onions", "Leeks", "Broccoli", "Cabbage"],
    harvest: ["Winter greens", "Kale", "Overwintered root vegetables", "Citrus"],
    prepareForNextMonth: ["Order seeds", "Add compost to beds", "Prune dormant fruit trees"],
  },
  February: {
    plantNow: ["Peas", "Spinach", "Lettuce", "Radishes", "Beets", "Carrots", "Chard"],
    startInTrays: ["Tomatoes (late February)", "Peppers", "Eggplant", "Broccoli"],
    harvest: ["Winter greens", "Citrus", "Kale"],
    prepareForNextMonth: ["Set up irrigation", "Prep tomato beds", "Build trellises"],
  },
  March: {
    plantNow: ["Peas", "Potatoes", "Carrots", "Beets", "Chard", "Lettuce", "Onion sets"],
    startInTrays: ["Tomatoes", "Peppers", "Eggplant", "Basil", "Squash", "Cucumbers"],
    harvest: ["Spring greens", "Early peas", "Broccoli", "Kale"],
    prepareForNextMonth: ["Watch for last frost", "Build tomato support structures"],
  },
  April: {
    plantNow: ["Beans", "Summer squash", "Beets", "Carrots", "Corn", "Chard"],
    startInTrays: ["Cucumbers", "Melons", "Sunflowers", "Zinnias"],
    harvest: ["Peas", "Lettuce", "Spring greens", "Asparagus"],
    prepareForNextMonth: ["Mulch beds", "Set watering schedule for summer"],
  },
  May: {
    plantNow: ["Beans", "Cucumbers", "Squash", "Corn", "Sunflowers", "Basil", "Zinnias"],
    startInTrays: [],
    harvest: ["Peas", "Lettuce", "Beets", "Carrots"],
    prepareForNextMonth: ["Transplant tomatoes and peppers", "Mulch everything", "Set up drip irrigation"],
  },
  June: {
    plantNow: ["Beans (succession)", "Cucumbers (succession)", "Okra", "Cowpeas", "Watermelon"],
    startInTrays: ["Broccoli for fall", "Cabbage for fall"],
    harvest: ["Zucchini", "Beans", "Cucumbers", "Early tomatoes", "Garlic"],
    prepareForNextMonth: ["Order garlic for fall", "Plan fall garden"],
  },
  July: {
    plantNow: ["Cowpeas", "Okra", "Beans (last succession)"],
    startInTrays: ["Broccoli", "Cabbage", "Kale for fall"],
    harvest: ["Tomatoes", "Peppers", "Eggplant", "Cucumbers", "Melons"],
    prepareForNextMonth: ["Order fall seeds", "Prep fall beds"],
  },
  August: {
    plantNow: ["Radishes (late August)", "Beans (last chance)"],
    startInTrays: ["Broccoli", "Kale", "Cabbage", "Chard"],
    harvest: ["Tomatoes (peak)", "Watermelon", "Peppers", "Winter squash"],
    prepareForNextMonth: ["Order garlic", "Clear spent beds", "Add compost"],
  },
  September: {
    plantNow: ["Carrots", "Beets", "Lettuce", "Radishes", "Chard", "Turnips"],
    startInTrays: ["Kale", "Spinach"],
    harvest: ["Tomatoes", "Peppers", "Pumpkins", "Winter squash", "Sweet potatoes"],
    prepareForNextMonth: ["Plant strawberries", "Prep garlic beds", "Transplant fall brassicas"],
  },
  October: {
    plantNow: ["Garlic", "Onion sets", "Peas", "Fava beans", "Spinach", "Lettuce", "Radishes"],
    startInTrays: [],
    harvest: ["Fall greens", "Winter squash", "Peppers (last)", "Pumpkins"],
    prepareForNextMonth: ["Cover crop empty beds", "Save seeds", "Mulch garlic"],
  },
  November: {
    plantNow: ["Garlic", "Fava beans", "Peas", "Spinach", "Kale", "Chard"],
    startInTrays: ["Onions (late November)"],
    harvest: ["Fall greens", "Broccoli", "Kale", "Root vegetables"],
    prepareForNextMonth: ["Protect tender plants from frost", "Order next year's seeds", "Mulch beds"],
  },
  December: {
    plantNow: ["Peas", "Fava beans", "Spinach", "Lettuce"],
    startInTrays: [],
    harvest: ["Winter greens", "Kale", "Chard", "Citrus", "Root vegetables"],
    prepareForNextMonth: ["Order seeds", "Plan bed layout", "Service irrigation"],
  },
};

// ─── Bay Area ──────────────────────────────────────────────────────────────────

const bayAreaMonths: Record<MonthName, MonthPlan> = {
  January: {
    plantNow: ["Peas", "Fava beans", "Spinach", "Lettuce", "Kale", "Chard", "Garlic", "Cilantro"],
    startInTrays: ["Onions", "Leeks", "Broccoli", "Cabbage"],
    harvest: ["Winter greens", "Kale", "Chard", "Citrus", "Broccoli"],
    prepareForNextMonth: ["Order seeds", "Amend beds with compost", "Plan layout"],
  },
  February: {
    plantNow: ["Peas", "Spinach", "Lettuce", "Radishes", "Beets", "Carrots", "Arugula", "Chard"],
    startInTrays: ["Tomatoes", "Peppers", "Eggplant", "Broccoli", "Basil"],
    harvest: ["Winter greens", "Citrus", "Broccoli", "Kale"],
    prepareForNextMonth: ["Prep summer beds", "Set up irrigation", "Build trellises"],
  },
  March: {
    plantNow: ["Peas", "Potatoes", "Beets", "Carrots", "Chard", "Lettuce", "Turnips"],
    startInTrays: ["Tomatoes", "Peppers", "Squash", "Cucumbers", "Melons", "Basil"],
    harvest: ["Spring greens", "Peas starting", "Broccoli", "Kale"],
    prepareForNextMonth: ["Watch fog patterns", "Don't rush warm-season transplants outdoors"],
  },
  April: {
    plantNow: ["Beans", "Beets", "Carrots", "Chard", "Potatoes (if not done)"],
    startInTrays: ["Cucumbers", "Summer squash", "Sunflowers", "Zinnias"],
    harvest: ["Peas", "Lettuce", "Spring greens", "Asparagus"],
    prepareForNextMonth: ["Harden off tomato starts before transplanting", "Check for aphids on spring crops"],
  },
  May: {
    plantNow: ["Beans", "Summer squash", "Sunflowers", "Zinnias", "Basil (later in month)"],
    startInTrays: [],
    harvest: ["Peas", "Lettuce", "Beets", "Spring greens"],
    prepareForNextMonth: ["Watch fog — tomatoes often wait until June here", "Plan succession plantings"],
  },
  June: {
    plantNow: ["Beans (succession)", "Cucumbers", "Summer squash", "Basil", "Zinnias", "Cosmos"],
    startInTrays: [],
    harvest: ["Zucchini", "Beans", "Early tomatoes (sunny spots)", "Herbs", "Lettuce"],
    prepareForNextMonth: ["Check for fog damage on tender plants", "Stake tomatoes"],
  },
  July: {
    plantNow: ["Beans (succession)", "Cucumbers (succession)", "Basil"],
    startInTrays: ["Broccoli for fall", "Kale", "Cabbage"],
    harvest: ["Tomatoes (in sun)", "Beans", "Cucumbers", "Zucchini", "Herbs"],
    prepareForNextMonth: ["Start fall planning", "Order garlic"],
  },
  August: {
    plantNow: ["Beans (last succession)", "Radishes"],
    startInTrays: ["Broccoli", "Kale", "Cabbage", "Chard"],
    harvest: ["Tomatoes", "Peppers", "Cucumbers", "Beans", "Basil"],
    prepareForNextMonth: ["Order garlic", "Clear summer beds", "Plan fall garden"],
  },
  September: {
    plantNow: ["Lettuce", "Spinach", "Radishes", "Carrots", "Beets", "Arugula", "Chard"],
    startInTrays: ["Kale", "Pac choi"],
    harvest: ["Tomatoes", "Peppers", "Squash", "Cucumbers (winding down)"],
    prepareForNextMonth: ["Plant strawberries", "Prep garlic beds", "Transplant fall brassicas"],
  },
  October: {
    plantNow: ["Garlic", "Onion sets", "Peas", "Fava beans", "Spinach", "Lettuce", "Kale"],
    startInTrays: [],
    harvest: ["Fall greens", "Tomatoes (last)", "Peppers (last)", "Winter squash"],
    prepareForNextMonth: ["Mulch garlic bed", "Cover crop empty beds", "Save seeds"],
  },
  November: {
    plantNow: ["Garlic (if not done)", "Fava beans", "Peas", "Spinach", "Kale", "Chard"],
    startInTrays: ["Onions"],
    harvest: ["Fall greens", "Broccoli", "Kale", "Chard"],
    prepareForNextMonth: ["Light frost protection for tender plants", "Order seeds for next year"],
  },
  December: {
    plantNow: ["Peas", "Fava beans", "Spinach", "Lettuce", "Kale"],
    startInTrays: [],
    harvest: ["Winter greens", "Kale", "Chard", "Citrus", "Broccoli"],
    prepareForNextMonth: ["Order seeds", "Plan bed rotations", "Rest and regroup"],
  },
};

// ─── Southern California ───────────────────────────────────────────────────────

const soCalMonths: Record<MonthName, MonthPlan> = {
  January: {
    plantNow: ["Peas", "Lettuce", "Spinach", "Kale", "Chard", "Radishes", "Beets", "Carrots", "Onions", "Garlic"],
    startInTrays: ["Tomatoes", "Peppers", "Eggplant (late January)", "Broccoli"],
    harvest: ["Winter greens", "Citrus (peak)", "Brassicas", "Root vegetables", "Herbs"],
    prepareForNextMonth: ["Order summer seeds", "Amend beds for spring", "Plan layout"],
  },
  February: {
    plantNow: ["Tomatoes (coastal mild areas)", "Beans (inland, late Feb)", "Peas", "Beets", "Carrots", "Lettuce", "Spinach"],
    startInTrays: ["Tomatoes", "Peppers", "Eggplant", "Cucumbers", "Basil"],
    harvest: ["Citrus", "Winter greens", "Brassicas", "Peas starting"],
    prepareForNextMonth: ["Set up irrigation", "Build tomato cages", "Prep summer beds"],
  },
  March: {
    plantNow: ["Beans", "Cucumbers", "Squash", "Tomatoes", "Peppers", "Basil", "Corn"],
    startInTrays: ["Melons", "Winter squash", "Sunflowers"],
    harvest: ["Peas", "Lettuce", "Broccoli", "Spring greens", "Citrus ending"],
    prepareForNextMonth: ["Mulch beds", "Set up summer watering schedule", "Watch for aphids"],
  },
  April: {
    plantNow: ["Beans", "Cucumbers", "Summer squash", "Watermelon", "Melons", "Corn", "Sunflowers", "Zinnias"],
    startInTrays: [],
    harvest: ["Tomatoes starting", "Peas (finishing)", "Spring greens", "Beets", "Carrots"],
    prepareForNextMonth: ["Watch heat — it can spike early", "Make sure drip irrigation is working"],
  },
  May: {
    plantNow: ["Okra", "Cowpeas", "Sweet potatoes", "More beans", "More cucumbers", "Basil"],
    startInTrays: ["Summer crops for succession"],
    harvest: ["Tomatoes", "Beans", "Zucchini", "Cucumbers", "Herbs"],
    prepareForNextMonth: ["Plan for summer heat — shade cloth, deep water"],
  },
  June: {
    plantNow: ["Cowpeas", "Okra", "Sweet potatoes", "Armenian cucumbers"],
    startInTrays: ["Broccoli for fall", "Cabbage"],
    harvest: ["Tomatoes", "Peppers", "Eggplant", "Cucumbers", "Melons starting", "Garlic"],
    prepareForNextMonth: ["Order garlic for fall", "Plan fall garden"],
  },
  July: {
    plantNow: ["Cowpeas", "Okra"],
    startInTrays: ["Broccoli for fall", "Kale", "Cabbage"],
    harvest: ["Tomatoes (peak)", "Peppers", "Melons", "Eggplant", "Beans"],
    prepareForNextMonth: ["Order fall seeds", "Prep fall beds"],
  },
  August: {
    plantNow: ["Beans (last succession)", "Radishes (late August)", "Cucumbers (last chance)"],
    startInTrays: ["Broccoli", "Cauliflower", "Kale", "Chard"],
    harvest: ["Tomatoes", "Peppers", "Watermelon", "Eggplant"],
    prepareForNextMonth: ["Order garlic", "Plan fall garden — it is big here", "Clear spent beds"],
  },
  September: {
    plantNow: ["Beans", "Carrots", "Beets", "Chard", "Lettuce", "Spinach", "Radishes"],
    startInTrays: ["Kale", "Pac choi", "Broccoli"],
    harvest: ["Tomatoes", "Peppers", "Winter squash", "Sweet potatoes"],
    prepareForNextMonth: ["Plant strawberries now", "Prep garlic bed", "Transplant fall brassicas"],
  },
  October: {
    plantNow: ["Garlic", "Onions", "Peas", "Fava beans", "Lettuce", "Spinach", "Kale", "Broccoli", "Cabbage", "Carrots", "Beets"],
    startInTrays: [],
    harvest: ["Fall greens starting", "Late tomatoes", "Peppers", "Pumpkins"],
    prepareForNextMonth: ["Mulch garlic", "Cover crop empty beds", "Save seeds"],
  },
  November: {
    plantNow: ["Garlic", "Peas", "Fava beans", "Onions", "Spinach", "Lettuce", "Kale", "Chard", "Carrots", "Beets"],
    startInTrays: ["Onions"],
    harvest: ["Fall greens", "Broccoli", "Chard", "Kale", "Citrus starting"],
    prepareForNextMonth: ["Order seeds", "Plan next year", "Light frost watch (inland)"],
  },
  December: {
    plantNow: ["Peas", "Fava beans", "Lettuce", "Spinach", "Kale", "Radishes", "Onions"],
    startInTrays: ["Onions", "Tomatoes (late December — you can start early here)"],
    harvest: ["Winter greens", "Citrus (peak)", "Kale", "Broccoli", "Root vegetables"],
    prepareForNextMonth: ["Order seeds early", "Plan spring layout", "Keep growing — you can"],
  },
};

// ─── Pacific Northwest ─────────────────────────────────────────────────────────

const pnwMonths: Record<MonthName, MonthPlan> = {
  January: {
    plantNow: ["Nothing outdoors — soil too cold and wet"],
    startInTrays: ["Onions", "Leeks (late January)", "Celery"],
    harvest: ["Kale", "Brussels sprouts", "Overwintered roots", "Hardy greens"],
    prepareForNextMonth: ["Order seeds", "Service tools", "Plan layout", "Read seed catalogs"],
  },
  February: {
    plantNow: ["Peas (late February, if soil workable)", "Spinach (late February)", "Kale"],
    startInTrays: ["Onions", "Leeks", "Broccoli", "Cabbage", "Cauliflower", "Tomatoes (late Feb)"],
    harvest: ["Kale", "Brussels sprouts", "Overwintered chard"],
    prepareForNextMonth: ["Prep beds when soil dries out", "Add compost", "Build cold frames if needed"],
  },
  March: {
    plantNow: ["Peas", "Spinach", "Lettuce", "Kale", "Beets", "Carrots", "Potatoes (late March)"],
    startInTrays: ["Tomatoes", "Peppers", "Eggplant", "Broccoli", "Basil"],
    harvest: ["Overwintered greens", "Peas starting", "Kale"],
    prepareForNextMonth: ["Prepare tomato beds", "Set up cold frames or row cover"],
  },
  April: {
    plantNow: ["Peas", "Lettuce", "Spinach", "Radishes", "Beets", "Carrots", "Chard", "Potatoes", "Onion sets"],
    startInTrays: ["Cucumbers", "Summer squash", "Basil"],
    harvest: ["Overwintered greens", "Peas", "Spring kale", "Asparagus"],
    prepareForNextMonth: ["Harden off tomato starts", "Get trellises up for peas"],
  },
  May: {
    plantNow: ["Beans (late May)", "Beets", "Carrots", "Chard", "More lettuce", "Nasturtiums"],
    startInTrays: ["Melons (short season varieties)", "Winter squash"],
    harvest: ["Peas", "Spring greens", "Asparagus", "Overwintered root crops"],
    prepareForNextMonth: ["Transplant tomatoes and peppers under cover first", "Watch for late frost"],
  },
  June: {
    plantNow: ["Beans", "Cucumbers", "Summer squash", "Zucchini", "Corn (early June)", "Basil", "Sunflowers", "Zinnias"],
    startInTrays: [],
    harvest: ["Peas (peak)", "Lettuce", "Spinach", "Beets", "Chard", "Herbs"],
    prepareForNextMonth: ["Transplant tomatoes outdoors now", "Succession plant lettuce"],
  },
  July: {
    plantNow: ["Beans (succession)", "Beets (for fall)", "Carrots (for fall)", "Lettuce"],
    startInTrays: ["Broccoli for fall", "Kale", "Cabbage"],
    harvest: ["Peas (finishing)", "Beans starting", "Cucumbers", "Zucchini", "Early tomatoes"],
    prepareForNextMonth: ["Order fall seeds", "Plan brassica timing"],
  },
  August: {
    plantNow: ["Radishes", "Spinach", "Lettuce", "Kale", "Chard", "Turnips", "Cilantro", "Beets"],
    startInTrays: ["Broccoli", "Cabbage for overwintering"],
    harvest: ["Tomatoes (peak — finally)", "Cucumbers", "Beans", "Zucchini", "Blueberries"],
    prepareForNextMonth: ["Order garlic", "Plan fall and overwintering crops"],
  },
  September: {
    plantNow: ["Spinach", "Kale", "Garlic (early)", "Lettuce", "Arugula", "Pac choi", "Radishes"],
    startInTrays: ["Onions for overwintering"],
    harvest: ["Tomatoes", "Peppers", "Winter squash", "Apples", "Beans"],
    prepareForNextMonth: ["Get garlic in before November", "Prep overwintering beds", "Harvest before frost"],
  },
  October: {
    plantNow: ["Garlic", "Fava beans", "Winter cover crops", "Onion sets", "Spinach", "Kale"],
    startInTrays: [],
    harvest: ["Winter squash", "Late tomatoes", "Greens", "Kale", "Beets"],
    prepareForNextMonth: ["Mulch garlic heavily", "Cover crop empty beds", "Clean up diseased plant material"],
  },
  November: {
    plantNow: ["Garlic (last chance)", "Cover crops"],
    startInTrays: [],
    harvest: ["Kale", "Brussels sprouts", "Hardy greens", "Overwintered roots"],
    prepareForNextMonth: ["Protect overwintering crops from hard frost", "Order next year's seeds", "Rest"],
  },
  December: {
    plantNow: ["Nothing"],
    startInTrays: ["Onions (late December for very early start)"],
    harvest: ["Kale", "Brussels sprouts", "Hardy leeks", "Stored squash and roots"],
    prepareForNextMonth: ["Order seeds — do it now", "Plan rotation", "Service tools"],
  },
};

// ─── Region Definitions ────────────────────────────────────────────────────────

export const regions: RegionData[] = [
  {
    id: "anderson-redding",
    name: "Anderson / Redding / Red Bluff Area",
    zone: "Zone 9b (roughly)",
    climateReality: [
      "Long, very hot summers — triple digits are normal in July and August",
      "Mild winters with light frost, but rarely hard freezes",
      "Very dry from May through October — irrigation is not optional",
      "Spring is short and fast — the window from planting to heat stress is narrow",
      "Fall is long and kind — some of the best growing happens September through November",
    ],
    growsWell: [
      "Sunflowers",
      "Okra",
      "Cowpeas",
      "Armenian cucumbers",
      "Lemon cucumbers",
      "Burpless cucumbers",
      "Watermelon",
      "Pumpkins",
      "Sweet potatoes",
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Basil",
      "Zinnias",
      "Cosmos",
      "Marigolds",
      "Figs",
      "Pomegranates",
      "Blackberries",
      "Grapes",
    ],
    seedsToStock: [
      "Sunflowers",
      "Okra",
      "Cowpeas",
      "Bush beans",
      "Pole beans",
      "Cucumbers",
      "Watermelon",
      "Pumpkins",
      "Winter squash",
      "Zucchini",
      "Tomatoes",
      "Peppers",
      "Basil",
      "Zinnias",
      "Cosmos",
      "Marigolds",
      "Kale",
      "Broccoli",
      "Cabbage",
      "Cauliflower",
      "Lettuce",
      "Spinach",
      "Carrots",
      "Beets",
      "Radishes",
      "Peas",
      "Cilantro",
      "Dill",
      "Garlic",
      "Onion",
      "Cover crop mix",
    ],
    directSowNow: [
      "Sunflowers",
      "Okra",
      "Cowpeas",
      "Bush beans",
      "Cucumbers",
      "Zinnias",
      "Cosmos",
      "Marigolds",
    ],
    startInTraysNow: [
      "Broccoli (for fall)",
      "Cabbage (for fall)",
      "Cauliflower (for fall)",
      "Kale (for fall)",
      "Collards (for fall)",
      "Fall herbs",
    ],
    transplantsToBuyNow: [
      "Basil",
      "Peppers",
      "Eggplant",
      "Heat-tolerant flowers",
      "Sweet potato slips",
    ],
    thisWeeksTasks: [
      "Water early in the morning before the heat builds",
      "Mulch any bare soil — exposed ground bakes and loses moisture fast",
      "Put shade cloth on new transplants for the first week",
      "Check drip irrigation emitters — clogged lines waste water and stress plants",
      "Start fall brassicas in trays now, even if it still feels too hot",
      "Pull weeds before they set seed — they will take over if you wait",
      "Prep strawberry beds — plant slips in September",
      "Plan your next succession of sunflowers",
      "Start thinking about soil prep for the giant pumpkin patch",
    ],
    prepareNext: [
      "Fall garden beds — clear summer crops and add compost",
      "Garlic order — place it early, good varieties sell out",
      "Onion planning for winter starts",
      "Strawberry patch expansion",
      "Compost system — build or improve it now",
      "Giant pumpkin patch preparation — deep beds, rich soil, start in fall",
      "Chicken manure composting system",
      "Cover crops for empty beds",
    ],
    heatFrostNotes: [
      "Heat is the main challenge here, not frost",
      "Deep, infrequent watering beats shallow watering every day — train roots to go down",
      "Fall crops need to start in trays when it still feels too hot outside — trust the timing",
      "Shade cloth (30–50%) can make a real difference for fall transplants going in while heat lingers",
      "Frost rarely causes serious damage, but it can show up November through February",
      "Cover tender plants if frost is forecast — citrus and basil are the most vulnerable",
    ],
    months: andersonMonths,
  },
  {
    id: "sacramento-valley",
    name: "Sacramento Valley",
    zone: "Zone 9a–9b",
    climateReality: [
      "Hot summers similar to the far north valley but with slightly more moderate highs",
      "Tule fog in winter — can persist for weeks and limit what grows",
      "Short spring planting window before heat sets in",
      "Excellent fall growing — one of the best seasons here",
      "Irrigation required May through October",
    ],
    growsWell: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Corn",
      "Beans",
      "Cucumbers",
      "Summer squash",
      "Watermelon",
      "Cantaloupes",
      "Sunflowers",
      "Zinnias",
      "Marigolds",
      "Okra",
      "Sweet potatoes",
      "Almonds",
      "Stone fruit",
      "Figs",
    ],
    seedsToStock: [
      "Tomatoes",
      "Peppers",
      "Beans",
      "Cucumbers",
      "Summer squash",
      "Winter squash",
      "Watermelon",
      "Corn",
      "Sunflowers",
      "Zinnias",
      "Basil",
      "Kale",
      "Broccoli",
      "Lettuce",
      "Spinach",
      "Carrots",
      "Beets",
      "Garlic",
      "Peas",
      "Cover crop mix",
    ],
    directSowNow: [
      "Beans",
      "Cucumbers",
      "Summer squash",
      "Sunflowers",
      "Zinnias",
      "Basil (late spring/summer)",
      "Okra",
    ],
    startInTraysNow: [
      "Broccoli (for fall)",
      "Cabbage (for fall)",
      "Kale (for fall)",
    ],
    transplantsToBuyNow: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Basil",
      "Sweet potato slips",
    ],
    thisWeeksTasks: [
      "Water deeply and less frequently",
      "Mulch summer beds to conserve moisture",
      "Check tomato stakes and cages",
      "Start fall brassicas in trays",
      "Pull bolting spring crops",
      "Plant succession beans",
    ],
    prepareNext: [
      "Fall garden beds",
      "Garlic order",
      "Cover crops for winter",
      "Strawberry patch",
      "Compost building",
    ],
    heatFrostNotes: [
      "Summer heat is the main challenge — plan for it, don't fight it",
      "Tule fog in December and January slows cool-season crops but rarely freezes them out",
      "Light frost possible November through February — protect basil and citrus",
      "Deep watering is more important than frequent watering",
    ],
    months: sacramentoMonths,
  },
  {
    id: "bay-area",
    name: "Bay Area",
    zone: "Zone 9b–10b (varies by location)",
    climateReality: [
      "Marine influence means mild, even temperatures most of the year",
      "Summer fog can limit sun-loving crops, especially near the coast",
      "Tomatoes and peppers need the warmest, most sheltered spots you have",
      "Cool-season crops thrive almost year-round",
      "Frost is rare but possible inland in winter",
    ],
    growsWell: [
      "Lettuce",
      "Kale",
      "Chard",
      "Broccoli",
      "Cabbage",
      "Cauliflower",
      "Peas",
      "Fava beans",
      "Artichokes",
      "Strawberries",
      "Citrus",
      "Herbs",
      "Sunflowers (sunnier spots)",
      "Beans",
      "Cucumbers (in warm spots)",
      "Tomatoes (in warm, sheltered spots)",
    ],
    seedsToStock: [
      "Lettuce",
      "Kale",
      "Chard",
      "Spinach",
      "Broccoli",
      "Cabbage",
      "Peas",
      "Fava beans",
      "Beets",
      "Carrots",
      "Turnips",
      "Radishes",
      "Beans",
      "Cucumbers",
      "Tomatoes",
      "Basil",
      "Cilantro",
      "Sunflowers",
      "Zinnias",
      "Nasturtiums",
      "Garlic",
    ],
    directSowNow: [
      "Beans",
      "Beets",
      "Carrots",
      "Lettuce",
      "Radishes",
      "Sunflowers",
      "Nasturtiums",
      "Zinnias",
    ],
    startInTraysNow: [
      "Broccoli (for fall)",
      "Kale",
      "Cabbage",
    ],
    transplantsToBuyNow: [
      "Tomatoes (choose heat-tolerant varieties)",
      "Peppers",
      "Basil",
      "Summer flowers",
    ],
    thisWeeksTasks: [
      "Find the sunniest spot in your yard — that's where tomatoes go",
      "Don't let fog-damp soil stay cold — warm it with black plastic or row cover",
      "Plant cool-season crops freely — they love it here",
      "Water less than you think — fog adds moisture",
      "Check for slugs and snails in damp weather",
      "Stake peas and beans before they need it",
    ],
    prepareNext: [
      "Fall planting bed prep",
      "Garlic (plant October)",
      "Strawberry expansion",
      "Overwintering greens plan",
      "Compost building",
    ],
    heatFrostNotes: [
      "Fog is the main limiting factor, not frost or heat",
      "Tomatoes, peppers, and eggplant need your warmest, most sheltered microclimate",
      "Frost can happen inland — protect tender plants November through March",
      "Coastal areas rarely see frost — you can grow greens almost year-round",
      "If you have a south-facing wall, use it for heat-lovers",
    ],
    months: bayAreaMonths,
  },
  {
    id: "southern-california",
    name: "Southern California",
    zone: "Zone 10a–11 (coastal to inland desert)",
    climateReality: [
      "Mild winters allow year-round growing if you plan for it",
      "Hot summers inland, cooler and foggier near the coast",
      "Irrigation is essential — very little natural summer rainfall",
      "Two peak growing seasons: spring and fall/winter",
      "Frost is rare coastal, possible inland in January and February",
    ],
    growsWell: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Avocados",
      "Citrus",
      "Strawberries",
      "Figs",
      "Watermelon",
      "Melons",
      "Cucumbers",
      "Beans",
      "Corn",
      "Sweet potatoes",
      "Okra",
      "Kale",
      "Chard",
      "Lettuce (fall through spring)",
      "Broccoli",
      "Artichokes",
      "Sunflowers",
      "Zinnias",
    ],
    seedsToStock: [
      "Tomatoes",
      "Peppers",
      "Cucumbers",
      "Beans",
      "Watermelon",
      "Squash",
      "Corn",
      "Okra",
      "Sweet potatoes",
      "Lettuce",
      "Kale",
      "Broccoli",
      "Cabbage",
      "Chard",
      "Peas",
      "Beets",
      "Carrots",
      "Garlic",
      "Onions",
      "Sunflowers",
      "Zinnias",
      "Basil",
    ],
    directSowNow: [
      "Beans",
      "Cucumbers",
      "Summer squash",
      "Corn",
      "Sunflowers",
      "Zinnias",
      "Basil",
      "Okra",
    ],
    startInTraysNow: [
      "Tomatoes (if not planted yet)",
      "Broccoli for fall (late summer)",
      "Cabbage for fall",
    ],
    transplantsToBuyNow: [
      "Tomatoes",
      "Peppers",
      "Eggplant",
      "Basil",
      "Sweet potato slips",
    ],
    thisWeeksTasks: [
      "Water consistently — plants that dry out under heat struggle to recover",
      "Mulch everything",
      "Start fall brassicas in trays — do it earlier than feels right",
      "Harvest anything ready — do not let things overripen in heat",
      "Check for spider mites in hot, dry conditions",
      "Plan your fall garden — it will be your best season",
    ],
    prepareNext: [
      "Fall garden — this is a major growing season here",
      "Garlic order",
      "Strawberry patch",
      "Cover crops for empty beds",
      "Compost system",
    ],
    heatFrostNotes: [
      "Inland: summer heat can be extreme — shade cloth and deep watering are essential",
      "Coastal: fog limits summer crops more than frost does",
      "Year-round growing is possible here with planning",
      "Fall and winter are peak seasons for brassicas, lettuce, and root vegetables",
      "Light frost inland in January — protect tender plants",
    ],
    months: soCalMonths,
  },
  {
    id: "pacific-northwest",
    name: "Pacific Northwest",
    zone: "Zone 7b–8b",
    climateReality: [
      "Short, cool summers — the window for heat-loving crops is narrow",
      "Rain from October through May — drainage matters as much as irrigation",
      "Late spring means tomatoes go in late and need a head start",
      "Cool-season crops are the strength of this climate",
      "Mildew and blight are real threats — airflow and variety selection matter",
    ],
    growsWell: [
      "Kale",
      "Chard",
      "Lettuce",
      "Spinach",
      "Broccoli",
      "Brussels sprouts",
      "Cabbage",
      "Cauliflower",
      "Peas",
      "Fava beans",
      "Beans (in warmer summers)",
      "Potatoes",
      "Beets",
      "Carrots",
      "Onions",
      "Garlic",
      "Blueberries",
      "Raspberries",
      "Strawberries",
      "Apples",
      "Tomatoes (with a head start)",
      "Cucumbers (in warm years)",
      "Sunflowers (in sun)",
    ],
    seedsToStock: [
      "Kale",
      "Chard",
      "Lettuce",
      "Spinach",
      "Broccoli",
      "Cabbage",
      "Brussels sprouts",
      "Peas",
      "Fava beans",
      "Beans",
      "Beets",
      "Carrots",
      "Potatoes",
      "Onions",
      "Garlic",
      "Tomatoes (short season varieties)",
      "Cucumbers",
      "Sunflowers",
      "Nasturtiums",
      "Cover crop mix",
    ],
    directSowNow: [
      "Beets",
      "Carrots",
      "Kale",
      "Chard",
      "Lettuce",
      "Radishes",
      "Spinach",
      "Beans (June)",
      "Peas (March-April)",
    ],
    startInTraysNow: [
      "Tomatoes (6-8 weeks before last frost)",
      "Peppers (8-10 weeks before last frost)",
      "Broccoli",
      "Cabbage",
      "Onions",
    ],
    transplantsToBuyNow: [
      "Tomatoes (short season varieties)",
      "Peppers",
      "Basil",
      "Broccoli and cabbage starts",
    ],
    thisWeeksTasks: [
      "Check drainage — soggy soil causes rot",
      "Plant cool-season crops as soon as soil is workable",
      "Get tomatoes started indoors early",
      "Cover brassicas against cabbage moths",
      "Thin carrots and beets — crowding limits root size",
      "Slug patrol — set traps in wet weather",
    ],
    prepareNext: [
      "Overwintering crops plan — plant in late summer",
      "Garlic (plant in September-October)",
      "Cover crop the garden for winter",
      "Compost building",
      "Raised bed drainage improvement if needed",
    ],
    heatFrostNotes: [
      "Frost possible October through April — watch the forecast",
      "Summer heat spikes can be brief and intense — have shade cloth ready",
      "Cool, wet springs mean planting later than the calendar suggests",
      "Row cover extends the season on both ends and keeps crops warmer",
      "Choose short-season tomato varieties (65 days or fewer) for reliability",
    ],
    months: pnwMonths,
  },
];

export const defaultRegionId = "anderson-redding";

export function getRegion(id: string): RegionData {
  return regions.find((r) => r.id === id) ?? regions[0];
}
